<?php

 /*Implementing hook menu*/

function registration_menu()
{
	$items['registration/user'] = array(
    'title'=>'Registration Page',
    'page callback'=>'drupal_get_form',
	'page arguments'=>array('register_user_form'),
	'access callback'=>'user_access',
	'access arguments'=> array('access content'),
	'type'=>MENU_CALLBACK,
  );
 
  return $items;
}

function register_user_form($form,&$form_state){
	// print_r(path_to_theme());
	// $results=db_query("SELECT {mail} FROM {users}")->fetchField(); 
	$query = new EntityFieldQuery();
		// $query->entityCondition('entity_type', 'user')->fieldCondition('field_firstname_value', 'user')->execute();
		$entity_type='user';
		$fields_info = field_info_instances($entity_type);
		
		
	
		echo '<pre>',print_r($fields_info[$entity_type],true),'</pre>';
		$form=array();
		
		// echo count($fields_info[$entity_type]);
		
		foreach($fields_info[$entity_type] as  $key => $val){
				
			// echo '<pre>',print_r($val,true),'</pre>';
			
			// echo '<pre>',print_r($val['widget']['weight'],true),'</pre>';
			/*Field setup for the form goes here*/
			$label=$val['label'];
						
			if($val['widget']['type']=='text_textfield'){
				$type='textfield';
			}
			
			if($val['display']['default']['type']=='hidden'){
				$type='hidden';
			}
			
			if($val['widget']['type']=='number_integer'){
				$type='number';
			}
			
			if($val['required']==1){
				$required="TRUE";	
			}
			else {
				$required="";
			}
			
			/*Actual form fields goes here*/
			
			$form[$label] = array(
	      		'#type' => $type,
	      		'#title' => t($label),
	      		'#required'=>$required
	    	);

		}
		echo '<br><br>';
		$form['submit'] = array(
	      		'#type' => 'submit', 
	      		'#value' => 'Sign In',
	      		'#id'=>'sub',
	      		'#prefix' => '<div class=submitDiv> ', 
		 	);
		return $form;
}

function register_user_form_validate($form,&$form_state){
	
	print('<pre>'.print_r($form_state['values'],1).'</pre>');die();
}


// function register_user_form_submit($form,&$form_state){
	// // var_dump($form);	
	// // $results=db_query("SELECT {name} FROM {users}")->fetchField();
	// // echo $results;
	// $fields=array(
		// 'mail'=>$form_state['values']['email'],
		// 'name'=>$form_state['values']['firstName'].' '.$form_state['values']['lastName'],
		// 'utm_src'=>$form_state['values']['utm_src'],
		// 'status'=>$form_state['values']['status'],
	// );
// 	
// 	
	 // $count = db_query('SELECT count(*) FROM {users} WHERE mail = :hook', array(':hook' => $form_state['values']['email']))->fetchField();
	 // if($count>0){
	 	// echo 'User email already exists';
	 // }
	 // else{
	 	// db_insert('users')->fields($fields)->execute();	
		// print_r(db_query('SELECT count* FROM {users} WHERE email = :hook', array(':hook' => $form_state['values']['email']))->fetchField()); 
	 // }
// 	 
	 // // $count = db_query('SELECT count(*) FROM {registration} WHERE email = :hook', array(':hook' => $form_state['values']['email']))->fetchField();
	 // // echo $count;
	 // // db_insert('registration')->fields($fields)->execute();
// 	 
	 // // if($count>0){
	 	// // db_update('registration')->fields($fields)->condition('mail',$form_state['values']['email'])->execute();
	 // // }
	 // // else{
// // 	 
	 // // }
	// // select (*)
	// // db_insert('users')->fields($fields)->execute();
	// // drupal_goto('<front>');
// }